---
- name: Step 1 - Collect system information from Linux hosts
  hosts: Linux
  become: yes
  gather_facts: false

  tasks:
    #   - name: Run yum update
    #    shell: yum update -y
    #     register: yum_update_output
    #    ignore_errors: true

    - name: Get current date
      command: date
      register: current_date

    - name: Get system uptime
      command: uptime
      register: system_uptime

    - name: Get last 15 installed/updated packages
      shell: rpm -qa --last | head -n 15
      register: recent_packages

    - name: Set collected data as fact
      set_fact:
        collected_data: |
          =====================================
          Host: {{ inventory_hostname }}
          -------------------------------------
          #          Command: yum update -y
          #          Output:
          #          {{ yum_update_output.stdout | default('N/A') }}

          Command: date
          Output:
          {{ current_date.stdout }}

          Command: uptime
          Output:
          {{ system_uptime.stdout }}

          Command: rpm -qa --last | head -n 15
          Output:
          {{ recent_packages.stdout }}
          =====================================


- name: Step 2 - Save all results to a single file on localhost
  hosts: localhost
  gather_facts: no

  vars:
    output_file: "/var/tmp/collect_artifacts.txt"

  tasks:
    - name: Combine outputs from all Linux hosts into one file
      copy:
        dest: "{{ output_file }}"
        content: |
          {% for host in groups['Linux'] %}
          {{ hostvars[host].collected_data }}

          {% endfor %}

    - name: Show location of saved file
      debug:
        msg: "Results saved to {{ output_file }}"


- name: Step 3 - Copy the file to a Windows workstation
  hosts: my_windows_pc
  gather_facts: no
  become: false

  tasks:
    - name: Copy final artifact file to Windows Downloads folder
      ansible.windows.win_copy:
        src: /var/tmp/collect_artifacts.txt
        dest: C:\Users\P-SVE7FZ\Downloads\collect_artifacts.txt
