# ============================================================
# Play – Send email with STARTTLS
# ============================================================
---
- name: Send email with STARTTLS
  hosts: localhost
  gather_facts: no
  collections:
    - community.general
  vars:
    smtp_server: "172.25.52.17"
    smtp_port: 25
    sender_email: "gps_backup_alerts@ibm.onmicrosoft.com"
    recipient_email: "sattar.bee.shaik@ibm.com"
    email_subject: "Linux Patch Report"
    email_body: |
      Hi Team,

      System {{ ansible_hostname }} has been successfully provisioned and the patch report is ready.

      Regards,
      Automation Team
  tasks:
    - name: Send email via SMTP with STARTTLS
      community.general.mail:
        host: "{{ smtp_server }}"
        port: "{{ smtp_port }}"
        to: "{{ recipient_email }}"
        from: "{{ sender_email }}"
        subject: "{{ email_subject }}"
        body: "{{ email_body }}"
        secure: starttls
        timeout: 10
        ehlohost: "{{ ansible_fqdn | default(ansible_hostname) }}"
