---
# ============================================================
# Play 1 – Collect list of available security patches
# ============================================================
- name: Step 1 - Generate security patch report from Linux servers
  hosts: Linux
  gather_facts: no
  tasks:
    - name: Run yum to get list of security updates
      shell: yum updateinfo list security || true
      register: patch_output

    - name: Save output to fact
      set_fact:
        patch_list: "{{ patch_output.stdout_lines | map('trim') | list }}"

# ============================================================
# Play 2 – Create CSV report on the Ansible Controller
# ============================================================
- name: Step 2 - Save patch report on Ansible control node as CSV
  hosts: localhost
  gather_facts: no
  vars:
    report_csv: "/var/tmp/security_patch_report.csv"
  tasks:
    - name: Save patch report to CSV with only host and RHSA lines
      copy:
        dest: "{{ report_csv }}"
        content: |
          Host,RHSA_Update
          {% for host in groups['Linux'] %}
          {% for line in hostvars[host].patch_list | default([]) %}
          {% if 'RHSA-' in line %}
          {{ host }},"{{ line | replace(',', ';') }}"
          {% endif %}
          {% endfor %}
          {% endfor %}

    - name: Show where CSV was saved
      debug:
        msg: "CSV report saved to {{ report_csv }}"

# ============================================================
# Play 3 – Copy report to Windows workstation (optional)
# ============================================================
- name: Step 3 - Copy CSV report to Windows workstation
  hosts: my_windows_pc
  gather_facts: no
  become: false
  tasks:
    - name: Copy report to Windows Downloads folder
      ansible.windows.win_copy:
        src: /var/tmp/security_patch_report.csv
        dest: C:\Users\P-SVE7FZ\Downloads\security_patch_report.csv

# ================================================================

- name: Sending an e-mail using StartTLS, remote server, custom EHLO, and timeout of 10 seconds
  community.general.mail:
    host: 172.25.52.17
    port: 25
    timeout: 10
    ehlohost: GPS_backup_alerts@ibm.onmicrosoft.com
    to: sattar.bee.shaik@ibm.com
    subject: Ansible-report
    body: System {{ ansible_hostname }} has been successfully provisioned.
    secure: starttls
