---
- name: Patch RHEL servers
  hosts: Linux
  become: true
  vars:
    exclude_packages: []   # default empty, can be overridden from inventory or extra vars

  tasks:
    - name: Upgrade all packages (yum or dnf)
      package:
        name: "*"
        state: latest
        exclude: "{{ exclude_packages }}"
      register: patching_result

    - name: Display patching results
      ansible.builtin.debug:
        msg: "{{ patching_result.results | default('System is up to date') }}"

    - name: Check if reboot is needed
      ansible.builtin.command: needs-restarting -r
      register: reboot_check
      changed_when: reboot_check.rc == 1
      failed_when: false
      check_mode: false

    - name: Reboot server if necessary
      ansible.builtin.reboot:
        reboot_timeout: 600
      when: reboot_check.rc == 1
