---
- name: Step 1 - Generate security patch report from Linux servers
  hosts: Linux
  gather_facts: no
  tasks:
    - name: Run yum to get list of security updates
      shell: yum updateinfo list security || true
      register: patch_output

    - name: Save output to fact
      set_fact:
        patch_list: "{{ patch_output.stdout_lines | map('trim') | list }}"

- name: Step 2 - Save patch report on Ansible control node as CSV
  hosts: localhost
  gather_facts: no
  vars:
    report_csv: "/var/tmp/security_patch_report.csv"

  tasks:
    - name: Save patch report to CSV
      copy:
        dest: "{{ report_csv }}"
        content: |
          Host,Security Updates
          {% for host in groups['Linux'] %}
          {{ host }},"{% for line in hostvars[host].patch_list %}{{ line }}; {% endfor %}"
          {% endfor %}

    - name: Show where CSV was saved
      debug:
        msg: "CSV report saved to {{ report_csv }}"

- name: Step 3 - Copy CSV report to Windows workstation
  hosts: my_windows_pc
  gather_facts: no
  become: false     # <-- important: disable become for Windows hosts
  tasks:
    - name: Copy report to Windows Downloads folder
      ansible.windows.win_copy:
        src: /var/tmp/security_patch_report.csv
        dest: C:\Users\P-SVE7FZ\Downloads\security_patch_report.csv
