---
# ============================================================
# Play 1 – Collect list of available security patches
# ============================================================
- name: Step 1 - Generate security patch report from Linux servers
  hosts: Linux
  gather_facts: no
  tasks:
    - name: Run yum to get list of security updates
      shell: yum updateinfo list security || true
      register: patch_output

    - name: Save output to fact
      set_fact:
        patch_list: "{{ patch_output.stdout_lines | map('trim') | list }}"

# ============================================================
# Play 2 – Create CSV report on the Ansible Controller
# ============================================================
- name: Step 2 - Save patch report on Ansible control node as CSV
  hosts: localhost
  gather_facts: no
  vars:
    report_csv: "/var/tmp/security_patch_report.csv"
  tasks:
    - name: Save patch report to CSV with only host and RHSA lines
      copy:
        dest: "{{ report_csv }}"
        content: |
          Host,RHSA_Update
          {% for host in groups['Linux'] %}
          {% for line in hostvars[host].patch_list | default([]) %}
          {% if 'RHSA-' in line %}
          {{ host }},"{{ line | replace(',', ';') }}"
          {% endif %}
          {% endfor %}
          {% endfor %}

    - name: Show where CSV was saved
      debug:
        msg: "CSV report saved to {{ report_csv }}"

# ============================================================
# Play 3 – Copy report to Windows workstation (optional)
# ============================================================
- name: Step 3 - Copy CSV report to Windows workstation
  hosts: my_windows_pc
  gather_facts: no
  become: false
  tasks:
    - name: Copy report to Windows Downloads folder
      ansible.windows.win_copy:
        src: /var/tmp/security_patch_report.csv
        dest: C:\Users\P-SVE7FZ\Downloads\security_patch_report.csv

# ================================================================
- name: Step 4 - Send email with STARTTLS
  hosts: localhost
  gather_facts: no
  collections:
    - community.general.mail
  vars:
    smtp_server: "172.25.52.17"
    smtp_port: 25
    sender_email: "gps_backup_alerts@ibm.onmicrosoft.com"
    recipient_email: "sattar.bee.shaik@ibm.com"
    email_subject: "Linux Patch Report"
    email_body: |
      Hi Team,

      System {{ ansible_hostname }} has been successfully provisioned and the patch report is ready.

      Regards,
      Automation Team
  tasks:
    - name: Send email via SMTP with STARTTLS
      community.general.mail:
        host: "{{ smtp_server }}"
        port: "{{ smtp_port }}"
        to: "{{ recipient_email }}"
        from: "{{ sender_email }}"
        subject: "{{ email_subject }}"
        body: "{{ email_body }}"
        secure: starttls
        timeout: 10
        ehlohost: "{{ ansible_fqdn | default(ansible_hostname) }}"
i
