---
- name: Step 1 - Generate security patch report from Linux servers
  hosts: Linux
  gather_facts: no
  tasks:
    - name: Run yum to get list of security updates
      shell: yum updateinfo list security
      register: patch_output

    - name: Save output to fact
      set_fact:
        patch_list: "{{ patch_output.stdout_lines | map('trim') | list }}"

- name: Step 2 - Save patch report and convert to Excel on control node
  hosts: localhost
  gather_facts: no
  vars:
    patch_report_txt: "/tmp/security_patch_report.txt"
    patch_report_xlsx: "/tmp/security_patch_report.xlsx"
    convert_script: "/home/aap-tower/Desktop/ansible-automation-platform-containerized-setup-bundle-2.5-15.1-x86_64/Patch/files/convert_txt_to_excel.py"
  tasks:
    - name: Save patch report as TXT
      copy:
        dest: "{{ patch_report_txt }}"
        content: |
          Security Patch List
          -------------------
          {% for host in groups['Linux'] %}
          Host: {{ host }}
          {% for line in hostvars[host].patch_list %}
          {{ line }}
          {% endfor %}
          {% endfor %}

    - name: Confirm TXT file exists
      stat:
        path: "{{ patch_report_txt }}"
      register: txt_stat

    - name: Fail if TXT not created
      fail:
        msg: "TXT report file not found at {{ patch_report_txt }}"
      when: not txt_stat.stat.exists

    - name: Convert TXT to Excel
      command:
        argv:
          - /usr/bin/python3
          - "{{ convert_script }}"
          - "{{ patch_report_txt }}"
          - "{{ patch_report_xlsx }}"

- name: Step 3 - Copy Excel report to Windows workstation
  hosts: my_windows_pc
  gather_facts: no
  tasks:
    - name: Copy Excel report to Windows machine
      ansible.windows.win_copy:
        src: "{{ patch_report_xlsx }}"
        dest: "C:\\Users\\P-SVE7FZ\\Downloads\\security_patch_report.xlsx"
