- name: Step 1 - Collect security patch list from Linux servers
  hosts: Linux
  gather_facts: false

  tasks:
    - name: Get security patch list from yum
      shell: yum updateinfo list security
      register: security_patches

    - name: Set per-host patch_output fact
      set_fact:
        patch_output: "{{ security_patches.stdout_lines | map('trim') | list }}"


- name: Step 2a - Create consolidated TXT report on control node
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Initialize report file
      copy:
        dest: "/tmp/security_patch_report.txt"
        content: "Hostname | Security Patches\n"
        force: yes

    - name: Append patch info for each host
      lineinfile:
        path: "/tmp/security_patch_report.txt"
        line: "{{ item.key }} | {{ item.value.patch_output | join('; ') }}"
        create: yes
      loop: "{{ hostvars | dict2items }}"
      when: item.value.patch_output is defined


- name: Step 2b - Convert TXT report to Excel
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Run Python script to convert TXT to Excel
      script: files/convert_txt_to_excel.py


- name: Step 3 - Copy Excel report to Windows workstation
  hosts: my_windows_pc
  gather_facts: false
  vars:
    ansible_become: false  # Do NOT escalate on Windows

  tasks:
    - name: Copy Excel report to Windows Downloads folder
      ansible.windows.win_copy:
        src: /tmp/security_patch_report.xlsx
        dest: C:\Users\P-SVE7FZ\Downloads\security_patch_report.xlsx
