---
# ============================================================
# Play 1 – Collect list of available security patches
# ============================================================
- name: Step 1 - Generate security patch report from Linux servers
  hosts: Linux
  gather_facts: no
  tasks:
    - name: Run yum to get list of security updates
      shell: yum updateinfo list security || true
      register: patch_output

    - name: Save output to fact
      set_fact:
        patch_list: "{{ patch_output.stdout_lines | map('trim') | list }}"

# ============================================================
# Play 2 – Create CSV report on the Ansible Controller
# ============================================================
- name: Step 2 - Save patch report on Ansible control node as CSV
  hosts: localhost
  gather_facts: no
  vars:
    report_csv: "/var/tmp/security_patch_report.csv"
  tasks:
    - name: Save patch report to CSV with only host and RHSA lines
      copy:
        dest: "{{ report_csv }}"
        content: |
          Host,RHSA_Update
          {% for host in groups['Linux'] %}
          {% for line in hostvars[host].patch_list | default([]) %}
          {% if 'RHSA-' in line %}
          {{ host }},"{{ line | replace(',', ';') }}"
          {% endif %}
          {% endfor %}
          {% endfor %}

    - name: Show where CSV was saved
      debug:
        msg: "CSV report saved to {{ report_csv }}"

# ============================================================
# Play 3 – Email the report using community.general.mail
# ============================================================
- name: Step 3 - Email the Linux patch CSV report
  hosts: localhost
  gather_facts: no
  vars:
    report_csv: "/var/tmp/security_patch_report.csv"
    sender_email: "GPS_backup_alerts@ibm.onmicrosoft.com"
    recipients:
      - "Sattar.Bee.Shaik@ibm.com"
    subject: "Linux Patch Report - Job #{{ tower_job_id | default('manual') }}"
    email_body: |
      Hi Team,

      Please find the attached list of patches for Linux shared servers.

      Regards,
      Automation Team

      Job #{{ tower_job_id | default('manual') }} details:
      https://platformhost/execution/jobs/playbook/{{ tower_job_id | default('manual') }}
  tasks:
    - name: Send email with attachment via SMTP
      community.general.mail:
        host: localhost
        port: 25
        to: "{{ recipients }}"
        from: "{{ sender_email }}"
        subject: "{{ subject }}"
        body: "{{ email_body }}"
        attach:
          - "{{ report_csv }}"
      delegate_to: localhost

# ============================================================
# Play 4 – Copy report to Windows workstation (optional)
# ============================================================
- name: Step 4 - Copy CSV report to Windows workstation
  hosts: my_windows_pc
  gather_facts: no
  become: false
  tasks:
    - name: Copy report to Windows Downloads folder
      ansible.windows.win_copy:
        src: /var/tmp/security_patch_report.csv
        dest: C:\Users\P-SVE7FZ\Downloads\security_patch_report.csv
