---
- name: Gather yum security updates from Linux servers
  hosts: all
  become: yes
  gather_facts: yes

  tasks:
    - name: Run yum updateinfo list security
      shell: yum updateinfo list security
      register: yum_security

    - name: Save output as JSON for report generation
      copy:
        content: |
          {
            "host": "{{ inventory_hostname }}",
            "fqdn": "{{ ansible_fqdn }}",
            "date": "{{ ansible_date_time.date }}",
            "output": {{ yum_security.stdout_lines | to_json }}
          }
        dest: "/tmp/yum_output_{{ inventory_hostname }}.json"


- name: Generate Excel report from collected JSON files
  hosts: localhost
  gather_facts: false
  vars:
    ansible_connection: local
    ansible_python_interpreter: /usr/bin/python3

  tasks:
    - name: Merge all JSON into a single Excel report
      script: files/generate_excel.py
      delegate_to: localhost
      run_once: true


- name: Copy Excel report to Windows workstation
  hosts: my_windows_pc
  gather_facts: false

  tasks:
    - name: Copy the Excel report to Windows Downloads folder
      ansible.windows.win_copy:
        src: /tmp/yum_security_report.xlsx
        dest: C:\Users\P-SVE7FZ\Downloads\yum_security_report.xlsx
