- name: Step 1 - Generate security patch report from Linux servers
  hosts: Linux
  gather_facts: no
  tasks:
    - name: Run yum to get list of security updates
      shell: yum updateinfo list security
      register: patch_output

    - name: Save output to fact
      set_fact:
        patch_list: "{{ patch_output.stdout_lines | map('trim') | list }}"

- name: Step 2 - Save patch report on Ansible control node
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Save patch report as TXT
      copy:
        dest: /tmp/security_patch_report.txt
        content: |
          Security Patch List
          -------------------
          {% for host in groups['Linux'] %}
          Host: {{ host }}
          {% for line in hostvars[host].patch_list %}
          {{ line }}
          {% endfor %}
          {% endfor %}
    - name: Convert TXT report to Excel
      command:
        argv:
          - /usr/bin/python3
          - /home/aap-tower/Desktop/ansible-automation-platform-containerized-setup-bundle-2.5-15.1-x86_64/Patch/files/convert_txt_to_excel.py

- name: Step 3 - Copy Excel report to Windows workstation
  hosts: my_windows_pc
  gather_facts: no
  tasks:
    - name: Copy Excel report to Windows machine
      ansible.windows.win_copy:
        src: /tmp/security_patch_report.xlsx
        dest: C:\Users\P-SVE7FZ\Downloads\security_patch_report.xlsx
