---
- name: Run `yum updateinfo list security` and capture output
  hosts: Linux
  become: yes

  tasks:
    - name: Get yum security update info
      shell: yum updateinfo list security
      register: security_output

    - name: Set fact for output
      set_fact:
        security_report: "{{ security_output.stdout }}"

- name: Copy report to Windows workstation
  hosts: my_windows_pc
  gather_facts: false

  tasks:
    - name: Save Linux patch report to file on Windows
      ansible.windows.win_copy:
        content: "{{ hostvars[item].security_report }}"
        dest: "C:\\Users\\P-SVE7FZ\\Downloads\\{{ item }}_yum_security_report.csv"
      loop: "{{ groups['all'] }}"
