---
- name: Search for available Windows patches
  hosts: all
  gather_facts: no
  tasks:
    - name: Check for available Windows updates
      ansible.windows.win_updates:
        state: searched
      register: update_result

    - name: Show available updates
      debug:
        msg: "{{ update_result.updates }}"

