---
- name: Search for available Windows updates (NO installation)
  hosts: all
  gather_facts: no
  tasks:

    - name: Ensure Windows Update service is running
      win_service:
        name: wuauserv
        start_mode: auto
        state: started

    - name: Check for available Windows updates
      ansible.windows.win_updates:
        state: searched
        category_names:
          - SecurityUpdates
          - CriticalUpdates
          - UpdateRollups
      register: update_result

    - name: Show available updates (if any)
      debug:
        msg: "{{ update_result.updates | default('No updates found') }}"
