---
- name: Detect pending Windows updates (pushed but not installed)
  hosts: all
  gather_facts: no
  tasks:

    - name: Ensure Windows Update service is running
      win_service:
        name: wuauserv
        start_mode: auto
        state: started

    - name: Search for pending updates (not yet installed)
      ansible.windows.win_updates:
        state: searched
      register: update_result

    - name: Show raw update search results
      debug:
        var: update_result

    - name: Show updates only (if any found)
      debug:
        msg: "{{ update_result.updates | default('No pending updates') }}"
